project:
  type: website
  output-dir: docs

website:
  title: "Kursusmateriale til Virksomhedsstrategi i et netv√¶rksperspektiv"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Install_guide.qmd
        text: "Install and setup R"
      - href: intro.qmd
        text: "Intro til R og Tidyverse"
      - href: kursusmateriale.qmd
        text: "Kursusmateriale"
  
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



